import { useState, useEffect } from 'react';
import type { DailySummary } from '../lib/db';
import { Play, Square } from 'lucide-react';

interface DailyBriefProps {
  summaries: DailySummary[];
}

export default function DailyBrief({ summaries }: DailyBriefProps) {
  const [isPlaying, setIsPlaying] = useState(false);
  const [synth] = useState(() => window.speechSynthesis);
  
  const fullText = "Here is your Morning News AI Briefing. " + 
    summaries.map(s => `${s.category} news. ${s.summary_text}`).join(' ');

  const handlePlayPause = () => {
    if (isPlaying) {
      synth.cancel();
      setIsPlaying(false);
    } else {
      if (summaries.length === 0) return;
      const utterance = new SpeechSynthesisUtterance(fullText);
      utterance.onend = () => setIsPlaying(false);
      utterance.onerror = () => setIsPlaying(false);
      synth.speak(utterance);
      setIsPlaying(true);
    }
  };

  // Stop talking when unmounting
  useEffect(() => {
    return () => {
      synth.cancel();
    };
  }, [synth]);

  if (summaries.length === 0) {
    return <p>No summaries generated for today.</p>;
  }

  return (
    <div className="daily-brief-grid">
      <div className="main-brief">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
          <h2>☀️ The Daily Download</h2>
          <button className="btn" onClick={handlePlayPause}>
            {isPlaying ? <><Square size={16} /> Stop Audio</> : <><Play size={16} /> Play Audio Briefing</>}
          </button>
        </div>

        {summaries.map((s, idx) => (
          <div key={idx} className="glass-panel summary-card">
            <h2 style={{ textTransform: 'capitalize' }}>{s.category}</h2>
            <div className="summary-content">
              {s.summary_text.split('\n').map((paragraph, i) => (
                <p key={i} style={{ marginBottom: '1rem' }}>{paragraph}</p>
              ))}
            </div>
          </div>
        ))}
      </div>
      <div className="sidebar-chat">
        <div className="glass-panel" style={{ padding: '1.5rem', position: 'sticky', top: '2rem' }}>
          <h3 style={{ marginBottom: '1rem' }}>About this briefing</h3>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
            These summaries are automatically generated by OpenAI GPT-4o based on the cluster of daily articles in each category. 
            This represents the true intelligence layer of the backend, completely replacing the naive article aggregation.
          </p>
        </div>
      </div>
    </div>
  );
}
